# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DQNSzczegolyTemplatka.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 252)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.replay_size_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.replay_size_spin.setMinimum(10)
        self.replay_size_spin.setMaximum(9999999)
        self.replay_size_spin.setObjectName("replay_size_spin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.replay_size_spin)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.learning_rate_spin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.learning_rate_spin.setDecimals(3)
        self.learning_rate_spin.setMinimum(0.01)
        self.learning_rate_spin.setMaximum(1.0)
        self.learning_rate_spin.setObjectName("learning_rate_spin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.learning_rate_spin)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.start_exploration_spin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.start_exploration_spin.setDecimals(3)
        self.start_exploration_spin.setMaximum(1.0)
        self.start_exploration_spin.setObjectName("start_exploration_spin")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.start_exploration_spin)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.exploration_decay_spin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.exploration_decay_spin.setDecimals(5)
        self.exploration_decay_spin.setMaximum(0.99)
        self.exploration_decay_spin.setObjectName("exploration_decay_spin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.exploration_decay_spin)
        self.mnimal_exploration_spin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.mnimal_exploration_spin.setDecimals(5)
        self.mnimal_exploration_spin.setMaximum(0.99)
        self.mnimal_exploration_spin.setObjectName("mnimal_exploration_spin")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.mnimal_exploration_spin)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.mini_batch_size = QtWidgets.QSpinBox(self.centralwidget)
        self.mini_batch_size.setMinimum(1)
        self.mini_batch_size.setMaximum(9999999)
        self.mini_batch_size.setObjectName("spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mini_batch_size)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DQN szczegóły"))
        self.label.setText(_translate("MainWindow", "Wilkość bufora replay"))
        self.replay_size_spin.setSuffix(_translate("MainWindow", " ruchów"))
        self.label_2.setText(_translate("MainWindow", "Współczynnik uczenia"))
        self.label_4.setText(_translate("MainWindow", "Wartość zmniejszająca poziom ekspolracji"))
        self.label_3.setText(_translate("MainWindow", "Początkowy wspólczynnik ekspolarcji"))
        self.label_5.setText(_translate("MainWindow", "Mnimalny poziom eksploracji"))
        self.label_6.setText(_translate("MainWindow", "Wielkość partii do nauki"))

